function coords_json = avatar_proto_coords_range
coord_s = [...
'{'...
    '"caption":"%s",'...
    '"range":{'...
        '"actual":{'...
            '"min":"%2.2f",'...
            '"max":"%2.2f"'...
         '},'...
        '"required":{'...
            '"min":"%2.2f",'...
            '"max":"%2.2f"'...
         '}'...
    '},'...
    '"actual":"%2.2f"'...
'}'...
];

coords_s = [...
    '{"command":"config"'...
    ',"coords":['...
        '%s'...
        ',%s'...
        ',%s'...
        ',%s'...
        ',%s'...
        ',%s'...
    ']}'...
];
coords_json = sprintf(...
    coords_s...
    , sprintf(coord_s, 'X',     -180,180, -150, 70, -34) ...
    , sprintf(coord_s, 'Y',     -180,180, -90, 90, -0) ...
    , sprintf(coord_s, 'Z',     -180,180, -90, 90, -0) ...
    , sprintf(coord_s, 'YAW',   -180,180, -90, 90, -0) ...
    , sprintf(coord_s, 'PITCH', -180,180, -90, 90, -0) ...
    , sprintf(coord_s, 'ROLL',  -180,180, -90, 90, -0) ...
)
% data = jsondecode(coords_json)