classdef avatar_proto < handle
   properties
       formatRequest = '{"command":"%s"}\n';
       formatArm = [
           '{' ...
                '"command": "ARM"' ...
                ', "timestamp": 1619009891000' ...
                ', "arm": 0'...
                ',"pos": {' ...
                    '"x": %2.2f' ...
                    ', "y": %2.2f' ...
                    ', "z": %2.2f' ...
                  '}' ...
               ', "rot": {' ...
                    '"r": %2.2f' ...
                    ', "p": %2.2f' ...
                    ', "y": %2.2f' ...
                 '}' ...
                ',"fingers": [%2.2f]' ...
            '}\n'
       ];
   end
   methods
        function handle = avatar_coord()
        end
        function delete(handle)
        end
        
        function data = queryConfig(handle)
            data = sprintf(handle.formatRequest,'CONFIG');
        end
        function data = queryStatus(handle)
            data = sprintf(handle.formatRequest,'STATUS');
        end
        function data = commandCalibrate(handle)
            data = sprintf(handle.formatRequest,'CALIBRATE');
        end
        function data = commandArm(handle, x,y,z,Y,p,r,f)
            data = sprintf(handle.formatArm, x,y,z,r,p,Y,f);
        end
   end
   
    methods (Access = private)
    end
end
