syms q5 q4 q3  Y  P  R

AQ3 = [ ...
        1   0       0;...
        0   cos(q3) -sin(q3);...
        0   sin(q3) cos(q3);...
       ];

AQ4 = [ ...
        cos(q4) 0   sin(q4);...
        0       1   0;...
        -sin(q4) 0   cos(q4);...
       ];
   
AQ5 = [ ...
        1   0       0;...
        0   cos(q5) -sin(q5);...
        0   sin(q5) cos(q5);...
       ];
   
A= simplify(AQ3*AQ4*AQ5)


AR = [ ...
        1   0       0;...
        0   cos(R) -sin(R);...
        0   sin(R) cos(R);...
       ];

AP = [ ...
        cos(-P) 0   sin(-P);...
        0       1   0;...
        -sin(-P) 0   cos(-P);...
       ];
   
AY = [ ...
        cos(Y) -sin(Y)   0;...
        sin(Y) cos(Y)   0;...
        0      0        1;...
       ];

 A2 = simplify(AY*AP*AR)
 

 