f3 = -89;
f4 = -89;
f5= -89;

q3=f3/180*pi;
q4=f4/180*pi;
q5=f5/180*pi;

% 
%  
% [          cos(q4),                           sin(q4)*sin(q5),                             cos(q5)*sin(q4)]
% [  sin(q3)*sin(q4), cos(q3)*cos(q5) - cos(q4)*sin(q3)*sin(q5), - cos(q3)*sin(q5) - cos(q4)*cos(q5)*sin(q3)]
% [ -cos(q3)*sin(q4), cos(q5)*sin(q3) + cos(q3)*cos(q4)*sin(q5),   cos(q3)*cos(q4)*cos(q5) - sin(q3)*sin(q5)]
%  
%  
% [ cos(P)*cos(Y), - cos(R)*sin(Y) - cos(Y)*sin(P)*sin(R),   sin(R)*sin(Y) - cos(R)*cos(Y)*sin(P)]
% [ cos(P)*sin(Y),   cos(R)*cos(Y) - sin(P)*sin(R)*sin(Y), - cos(Y)*sin(R) - cos(R)*sin(P)*sin(Y)]
% [        sin(P),                          cos(P)*sin(R),                          cos(P)*cos(R)]

 P = asin( -cos(q3)*sin(q4))
 R =	atan2(  cos(q5)*sin(q3) + cos(q3)*cos(q4)*sin(q5) ,  cos(q3)*cos(q4)*cos(q5) - sin(q3)*sin(q5) )
 Y = atan2(   sin(q3)*sin(q4), cos(q4) )

    

AQ3 = [ ...
        1   0       0;...
        0   cos(q3) -sin(q3);...
        0   sin(q3) cos(q3);...
       ];

AQ4 = [ ...
        cos(q4) 0   sin(q4);...
        0       1   0;...
        -sin(q4) 0   cos(q4);...
       ];
   
AQ5 = [ ...
        1   0       0;...
        0   cos(q5) -sin(q5);...
        0   sin(q5) cos(q5);...
       ];
   
A= AQ3*AQ4*AQ5


AR = [ ...
        1   0       0;...
        0   cos(R) -sin(R);...
        0   sin(R) cos(R);...
       ];

AP = [ ...
        cos(-P) 0   sin(-P);...
        0       1   0;...
        -sin(-P) 0   cos(-P);...
       ];
   
AY = [ ...
        cos(Y) -sin(Y)   0;...
        sin(Y) cos(Y)   0;...
        0      0        1;...
       ];

 A2 = AY*AP*AR
 

 A2-A